version: "3.7"
services:
    app:
        build:
            args:
                user: lahiru
                uid: 1000
            context: .
            dockerfile: Dockerfile
        container_name: pharmacy-system-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: pharmacy-system-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - 3308:3306
        volumes:
            - ./mysql-data:/var/lib/mysql
        networks:
            - laravel

    nginx:
        image: nginx:1.17-alpine
        container_name: pharmacy-system-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

networks:
    laravel:
        external: true
